name: Demo Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  list-files:
    runs-on: ubuntu-slim
    steps:
      - name: Download the Repository code from Github
        uses: actions/checkout@v4
      
      - name: List all the files in the Repository
        run: |
          echo "Listing all the files in the Repository"
          ls -R
