name: Demo Pipeline

run-name: "Demo Pipeline Run ${{ github.run_number}} by ${{ github.actor }}"

on:
  push:
    branches:
      - 'main'
      - 'feat/**'

jobs:
  first-job:
    runs-on: ubuntu-slim
    steps:
      - name: Print the name of the job
        run: echo "Hello from first job"
  
  second-job:
    runs-on: ubuntu-slim
    needs: first-job
    steps:
      - name: Print the name of the job
        run: echo "Hello from the second job"

  third-job:
    runs-on: ubuntu-slim
    needs: second-job
    steps:
      - name: Print the name of the job
        run: echo "Hello from the third job"

  fourth-job:
    runs-on: ubuntu-slim
    needs: second-job
    steps:
      - name: Print the name of the job
        run: echo "Hello from the fourth job"
